### 계좌 생성
POST http://localhost:8100/accounts/1001
X-User-Id: user123

### 입금
POST http://localhost:8100/accounts/1001/deposit?amount=10000
X-User-Id: user123

### 출금
POST http://localhost:8100/accounts/1001/withdraw?amount=5000
X-User-Id: user123

### 계좌 이체
POST http://localhost:8100/accounts/transfer
X-User-Id: user123
Content-Type: application/json

{
  "fromAccountId": "1001",
  "toAccountId": "1002",
  "amount": 1000
}